---
  header_logo_text: World Ichneumonidae Database (WID)
  header_logo_url: /images/logoWid_wasp.png
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about1

    - label: Subfamilies
      link: /subfamilies

    - label: News
      submenu: 
        - label: New References
          link: /RecentReferences
        - label: New Taxa
          link: /RecentTaxa

    - label: Collaborate with us
      link: /collaboration
    
    - label: How to Cite
      link: /cite