---
  project_name: 'World Ichneumonidae Database (WID)'
  project_citation: 'World Ichneumonidae Database (WID)'
  project_url: https://worldichneumonidae.com
  project_authors: Dal Pos D.; Behm R.; Reshchikov A.; Santos A.; Herrera-Flórez A.; De Ketelaere A.; Verheyde F.; Broad G.; Onody H.; Bendixen L.; Araujo R.; van Noort S.; Pénigot W.; Di Giovanni F. 