taxa_page:
  overview:
    panels:
      - - - panel:gallery
          - panel:type
          - panel:type-specimen
          - panel:nomenclature
          - panel:nomenclature-references

        - - panel:map
          - panel:descendants
          - panel:scrutiny
          - panel:content
          - panel:keys
          - panel:etymology
          - panel:gbif
          - panel:statistics
  specimen_records:
    rank_group: ['SpeciesGroup']
    panels:
      - - - panel:specimen-records
  field_occurrences:
    rank_group: ['SpeciesGroup']
    panels:
      - - - panel:field-occurrences
  inaturalist:
    label: 'iNaturalist'
    rank_group: ['GenusGroup', 'SpeciesGroup']
    panels:
      - - - id: panel:inaturalist
            bind:
              parameters:
                taxon_id: 47201
